seed: 33
policy: # only works for MlpPolicy right now
  pi_hid_sizes: [256, 128, 64]
  vf_hid_sizes: [256, 128, 64]
  activation: selu # can be elu, relu, selu, crelu, lrelu, tanh, sigmoid
learn:
  agent_name: gogoro_steering_command
  resume: 0
  test: False
  print_log: True
  save_interval: 200 # check for potential saves every this many iterations

  # rollout params
  max_iterations: 30000

  # training params
  cliprange: 0.2
  ent_coef: 0
  nsteps: 32
  noptepochs: 10
  max_grad_norm: 1
  nminibatches: 2 # this is per agent
  optim_stepsize: 3.0e-5 # 3e-4 isefault for single agent training with constant schedule
  schedule: adaptive # could be adaptive or linear
  gamma: 0.99
  lam: 0.95
  init_noise_std: 0.8

  log_interval: 1
